# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [5]:
#%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [6]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [7]:
np.__version__

'1.24.4'

#### 3. Create a null vector of size 10 (★☆☆)

In [10]:
arr = np.zeros(10)
print(f"Null Vector of size 10: {arr}")

Null Vector of size 10: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [14]:
print(f"total number of elements: {arr.size}") #get total number of elements
print(f"size of an array: {arr.itemsize}") #get size bytes of each element of teh array
print(f"Memory size: {arr.nbytes}bytes ") #get number of bytes occupied by the entire array object in memory 

total number of elements: 10
size of an array: 8
Memory size: 80bytes 


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [106]:
np.add?
np.info(np.add)
help(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [16]:
arr1 = np.zeros(10, dtype= np.int16)
arr1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [18]:
arr1[4] = 1
print(f"Array: {arr1}")

Array: [0 0 0 0 1 0 0 0 0 0]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [20]:
arr1 = np.random.randint(low= 10, high = 49, size = 10)
arr1

array([14, 10, 16, 21, 24, 30, 15, 38, 19, 38])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [23]:
arr2 = arr1[::-1]
arr2 

array([38, 19, 38, 15, 30, 24, 21, 16, 10, 14])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [33]:
matrix = np.random.randint(low = 0, high=8, size=(3,3))
matrix

array([[5, 4, 3],
       [7, 0, 3],
       [1, 1, 6]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [37]:
arr = np.array([1,2,0,0,4,0])
non_zero = np.where(arr==0)
print(f"Indices of non-zero elements in the array: {non_zero}")

Indices of non-zero elements in the array: (array([2, 3, 5], dtype=int64),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [38]:
identity_matrix = np.eye(3,3, dtype = np.int8)
identity_matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [41]:
arr = np.random.rand(3,3,3)
arr

array([[[0.81692832, 0.86597485, 0.24110835],
        [0.92803463, 0.3462497 , 0.28175454],
        [0.2070206 , 0.88685943, 0.87075953]],

       [[0.12621952, 0.17460188, 0.74376887],
        [0.58235792, 0.97948371, 0.87103979],
        [0.80446964, 0.50208492, 0.9033981 ]],

       [[0.27578264, 0.63531034, 0.39207434],
        [0.93552198, 0.75472383, 0.52734324],
        [0.6735788 , 0.10320785, 0.35297284]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [43]:
array1 = np.random.rand(10,10)
print("Array: ", array1)
print("Minimum Value of an Array: ", np.min(array1))
print("Maximum Value of an Array: ", np.max(array1))

Array:  [[0.06144102 0.16702556 0.69748689 0.7914207  0.89629992 0.18639436
  0.17519489 0.57219827 0.62897123 0.08099738]
 [0.53528587 0.12907584 0.86111805 0.45229888 0.05951452 0.998808
  0.69387377 0.46600872 0.53802039 0.83146042]
 [0.75248521 0.55025541 0.94573005 0.57008103 0.022728   0.49978639
  0.38476399 0.79657892 0.82672878 0.6947815 ]
 [0.11121242 0.8105644  0.2316719  0.22342037 0.63411658 0.79863789
  0.09768501 0.02943878 0.05772273 0.16982789]
 [0.58355067 0.78028048 0.27228157 0.05560283 0.5315438  0.28679252
  0.55337002 0.16317419 0.83980621 0.51058123]
 [0.32156803 0.98213631 0.2320172  0.10131096 0.64157392 0.42737171
  0.34787754 0.16023703 0.1508339  0.05312781]
 [0.06140107 0.30766317 0.49787363 0.04795892 0.16051458 0.75270989
  0.56415069 0.96930887 0.36198601 0.07747202]
 [0.73040202 0.87296875 0.95901277 0.13321233 0.3916591  0.15412424
  0.5990409  0.5934107  0.91189433 0.42473116]
 [0.61291373 0.21104243 0.68428117 0.90947405 0.10974693 0.64077697
  0.32

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [48]:
arra1 = np.random.rand(30)
print("Random Vector of size 30: ", arra1)
print("mean value of the vector: ", np.mean(arra1))

Random Vector of size 30:  [0.67853684 0.16512175 0.03762491 0.15310014 0.0077826  0.06144598
 0.91291997 0.77629239 0.7095656  0.72028276 0.44901261 0.69431234
 0.51157309 0.08157495 0.99326881 0.83992912 0.2618847  0.89069607
 0.45301707 0.6527872  0.89261732 0.48861726 0.37419328 0.58725367
 0.8519628  0.840124   0.02110893 0.18443457 0.92805886 0.17903632]
mean value of the vector:  0.5132711972231813


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [95]:
matr_2d = np.array([[1,1,1,1],[1,0,0,1],[1,0,0,1],[1,1,1,1]])
matr_2d

array([[1, 1, 1, 1],
       [1, 0, 0, 1],
       [1, 0, 0, 1],
       [1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [103]:
np.pad(matr_2d, 1, 'constant', constant_values = 0)

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 1, 0],
       [0, 1, 0, 0, 1, 0],
       [0, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [51]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [53]:
diag_matrix = np.eye(5,5, dtype=np.int8)
diag_matrix

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [55]:
for i in range(1,5):
    diag_matrix[i, i-1] = i
print(diag_matrix)
    

[[1 0 0 0 0]
 [1 1 0 0 0]
 [0 2 1 0 0]
 [0 0 3 1 0]
 [0 0 0 4 1]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [91]:
mat1 = np.zeros((8,8), dtype = np.int16)
mat1

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int16)

In [92]:
print(len(mat1))
for i in range(8):
    for j in range(0,8):
        mat1[i][j] = (i+j)%2
        print(mat1)
print(f"Checkboard filled matrix 8x8: {mat1}")

8
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 1 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 1 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 1 0 1 0 1 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 1 0 1 0 1 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [125]:
shape_array = np.random.rand(6,7,8)
print("(6,7,8) shape array: ", shape_array)
flat_array = shape_array.flatten()
print("flat_array: ", flat_array, flat_array.size)

flat_index = flat_array[99]
print("Flat_array_index: ", flat_index)
array_index = np.where(shape_array==flat_index)
print("The index(x,y,z) of the 100th element is: ", array_index)


(6,7,8) shape array:  [[[0.72875061 0.95836906 0.20986921 0.42180173 0.9966247  0.04088405
   0.0832881  0.44735538]
  [0.95305774 0.40094401 0.05907588 0.22252014 0.87490636 0.72100381
   0.9465224  0.22772711]
  [0.29612912 0.55788019 0.10242452 0.02712001 0.78507671 0.1725974
   0.69675823 0.14817926]
  [0.2641356  0.65631144 0.17996144 0.15079311 0.71998844 0.41968567
   0.85707459 0.67486233]
  [0.73013846 0.47421523 0.2700896  0.10962635 0.30579461 0.64341368
   0.12044924 0.59459505]
  [0.69899252 0.89215542 0.11934482 0.75824612 0.76266256 0.218761
   0.58006373 0.07336858]
  [0.8345372  0.93042236 0.74474121 0.23768579 0.20398766 0.07222202
   0.89715422 0.63867944]]

 [[0.17066665 0.50633165 0.4592198  0.43131741 0.23736035 0.29866702
   0.05735881 0.6574192 ]
  [0.15101777 0.41663844 0.71653031 0.77249871 0.21094619 0.98710407
   0.20727    0.6316693 ]
  [0.86114554 0.77902823 0.03824422 0.72282249 0.87056316 0.38012357
   0.79434312 0.1260635 ]
  [0.68118528 0.90383756 0.46

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)